// app/utils/pdfGenerator.ts
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Booking } from '../(activities)/profile/page'; // تأكد أن لديك نفس الـ interface هنا

export const generateBookingPDF = (booking: Booking) => {
  const doc = new jsPDF();

  // 🎨 اللون الأساسي Teal-500
  const teal500: [number, number, number] = [20, 184, 166];

  // 🛫 العنوان مع تصميم احترافي
  doc.setFontSize(26);
  doc.setTextColor(...teal500);
  doc.text('✈ Flight Reservation Ticket', 14, 20);

  // خط فاصل
  doc.setDrawColor(...teal500);
  doc.setLineWidth(1);
  doc.line(14, 25, 196, 25);

  // 📝 جدول معلومات الحجز
  const bookingData = [
    ['Reservation ID', booking.id],
    ['Flight', booking.flight],
    ['Gender', booking.gender],
    ['Date of Birth', booking.date_of_birth || 'Not specified'],
    ['Nationality', booking.nationality || 'Not specified'],
    ['Email', booking.email],
    ['Phone Number', booking.phone_number || 'Not specified'],
    ['Seats Booked', booking.seats_booked],
    ['Travel Class', booking.travel_class],
    ['Booking Date', new Date(booking.booking_date).toLocaleString('en-US')],
  ];

  autoTable(doc, {
    startY: 32,
    head: [['Field', 'Details']],
    body: bookingData,
    theme: 'grid',
    headStyles: { 
      fillColor: teal500 as [number, number, number], 
      textColor: 255, 
      halign: 'center', 
      fontSize: 12 
    },
    bodyStyles: { fontSize: 11, valign: 'middle' },
    alternateRowStyles: { fillColor: [230, 255, 253] }, // خلفية صفوف بلون فاتح
  });

  // 🖋 توقيع / Footer يشبه التذكرة
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(12);
  doc.setTextColor(...teal500);
  doc.text('Thank you for choosing our airline!', 14, pageHeight - 20);
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text('Generated by My Flight Booking System', 14, pageHeight - 12);

  // 💾 تنزيل الملف
  doc.save(`booking_${booking.id}.pdf`);
};
